channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pyqt>=5.12
  - pip
  - h5py>=2.10.0
  - pillow
  - psycopg2
  - sqlalchemy=1.3.11
  - matplotlib
  - jupyter
  - pandas
  - seaborn
  - scipy
  - pyyaml
  - numba
  - scikit-image
  - scikit-learn
  - statsmodels
  - pip:
    - lmfit
    - pyqtgraph
    - git+https://github.com/alleninstitute/neuroanalysis
