channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pyqt
  - pip
  - h5py
  - pillow
  - psycopg2
  - sqlalchemy
  - matplotlib
  - pandas
  - scipy
  - pyyaml
  - scikit-image
  - scikit-learn
  - statsmodels
  - numpydoc
  - sphinx_rtd_theme
  - pip:
    - lmfit
    - git+https://github.com/pyqtgraph/pyqtgraph
    - git+https://github.com/alleninstitute/neuroanalysis
    
