dependencies:
  - python=3
  - pyqt
  - pip
  - h5py
  - pillow
  - psycopg2
  - sqlalchemy
  - matplotlib
  - pandas
  - scipy
  - numba
  - pyyaml
  - scikit-image
  - scikit-learn
  - statsmodels
  - pip:
    - lmfit
    
    
